v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
N -750 -320 -650 -320 {
lab=VDD}
N -300 -320 -200 -320 {
lab=Vbias}
N -470 -190 -370 -190 {
lab=CLK}
N -160 -190 -60 -190 {
lab=EN}
N -750 -190 -650 -190 {
lab=Vin}
N -710 70 -710 120 {
lab=Vin}
C {SAR-ADC-using-Sky130-PDK.sym} -470 130 0 0 {name=x1}
C {devices/code_shown.sym} -1620 -280 0 0 {name=CONTROL only_toplevel=false value=".control
tran 0.5u 34u uic
set wr_singlescale
wrdata /home/samantha/cace/SAR-ADC-using-Sky130-PDK/runs/RUN_2025-08-20_23-09-23/parameters/Power/run_02/transient_2.data -I(VVDD)
quit
.endc
"}
C {devices/code_shown.sym} -1630 -560 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file transient_2
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the DAC.  Include both current through vdd and VREFH

.include /home/samantha/cace/SAR-ADC-using-Sky130-PDK/netlist/schematic/SAR-ADC-using-Sky130-PDK.spice
.include /usr/local/share/pdk/sky130A/libs.ref/sky130_fd_sc_hvl/spice/sky130_fd_sc_hvl.spice

.lib /usr/local/share/pdk/sky130A/libs.tech/combined/sky130.lib.spice tt

.option TEMP=27
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/vsource.sym} -750 -290 0 0 {name=VVDD value="DC 1.8" savecurrent=false}
C {devices/lab_pin.sym} -650 -320 0 1 {name=p33 sig_type=std_logic lab=VDD}
C {gnd.sym} -750 -260 0 0 {name=l2 lab=GND}
C {gnd.sym} -470 -260 0 0 {name=l3 lab=GND}
C {devices/vsource.sym} -470 -290 0 0 {name=VVGND value="DC 0" savecurrent=false}
C {devices/lab_pin.sym} -470 -320 0 1 {name=p1 sig_type=std_logic lab=VGND}
C {devices/lab_pin.sym} -710 -70 0 0 {name=p2 sig_type=std_logic lab=VDD}
C {devices/lab_pin.sym} -710 10 0 0 {name=p3 sig_type=std_logic lab=VGND}
C {devices/vsource.sym} -300 -290 0 0 {name=VVbias value="DC -0.8" savecurrent=false}
C {devices/lab_pin.sym} -200 -320 0 1 {name=p4 sig_type=std_logic lab=Vbias}
C {gnd.sym} -300 -260 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} -710 -50 0 0 {name=p5 sig_type=std_logic lab=Vbias}
C {devices/vsource.sym} -470 -160 0 0 {name=VCLK value="PULSE(1.8 0 0 500p 500p 1u 2u)" savecurrent=false}
C {devices/lab_pin.sym} -370 -190 0 1 {name=p6 sig_type=std_logic lab=CLK}
C {gnd.sym} -470 -130 0 0 {name=l4 lab=GND}
C {devices/vsource.sym} -160 -160 0 0 {name=VEN value="PULSE(1.8 0 0 500ps 500ps 1u 0)" savecurrent=false}
C {devices/lab_pin.sym} -60 -190 0 1 {name=p7 sig_type=std_logic lab=EN}
C {gnd.sym} -160 -70 0 0 {name=l5 lab=GND}
C {devices/lab_pin.sym} -710 -30 0 0 {name=p8 sig_type=std_logic lab=CLK}
C {devices/lab_pin.sym} -710 -10 0 0 {name=p9 sig_type=std_logic lab=EN}
C {devices/vsource.sym} -750 -160 0 0 {name=VVin value="DC 0.4" savecurrent=false}
C {devices/lab_pin.sym} -650 -190 0 1 {name=p10 sig_type=std_logic lab=Vin}
C {gnd.sym} -750 -130 0 0 {name=l6 lab=GND}
C {devices/lab_pin.sym} -710 70 0 0 {name=p11 sig_type=std_logic lab=Vin}
C {devices/res.sym} -130 50 2 0 {name=Rout
value=100000000.0
device=resistor}
C {devices/res.sym} 10 50 2 0 {name=Rout1
value=100000000.0
device=resistor}
C {devices/res.sym} 160 50 2 0 {name=Rout2
value=100000000.0
device=resistor}
C {devices/res.sym} 310 50 2 0 {name=Rout3
value=100000000.0
device=resistor}
C {devices/res.sym} -130 180 2 0 {name=Rout4
value=100000000.0
device=resistor}
C {devices/res.sym} 10 180 2 0 {name=Rout5
value=100000000.0
device=resistor}
C {devices/res.sym} 160 180 2 0 {name=Rout6
value=100000000.0
device=resistor}
C {devices/res.sym} 310 180 2 0 {name=Rout7
value=100000000.0
device=resistor}
C {gnd.sym} -130 80 0 0 {name=l7 lab=GND}
C {gnd.sym} 10 80 0 0 {name=l8 lab=GND}
C {gnd.sym} 160 80 0 0 {name=l9 lab=GND}
C {gnd.sym} 310 80 0 0 {name=l10 lab=GND}
C {gnd.sym} -130 210 0 0 {name=l11 lab=GND}
C {gnd.sym} 10 210 0 0 {name=l12 lab=GND}
C {gnd.sym} 160 210 0 0 {name=l13 lab=GND}
C {gnd.sym} 310 210 0 0 {name=l14 lab=GND}
C {devices/lab_pin.sym} -320 40 0 1 {name=p12 sig_type=std_logic lab=Q7}
C {devices/lab_pin.sym} -320 60 0 1 {name=p13 sig_type=std_logic lab=Q6}
C {devices/lab_pin.sym} -320 80 0 1 {name=p14 sig_type=std_logic lab=Q5}
C {devices/lab_pin.sym} -320 100 0 1 {name=p15 sig_type=std_logic lab=Q4}
C {devices/lab_pin.sym} -320 120 0 1 {name=p16 sig_type=std_logic lab=Q3}
C {devices/lab_pin.sym} -320 140 0 1 {name=p17 sig_type=std_logic lab=Q2}
C {devices/lab_pin.sym} -320 160 0 1 {name=p18 sig_type=std_logic lab=Q1}
C {devices/lab_pin.sym} -320 180 0 1 {name=p19 sig_type=std_logic lab=Q0}
C {devices/lab_pin.sym} 10 20 0 0 {name=p21 sig_type=std_logic lab=Q6}
C {devices/lab_pin.sym} 160 20 0 0 {name=p22 sig_type=std_logic lab=Q5}
C {devices/lab_pin.sym} 310 20 0 0 {name=p23 sig_type=std_logic lab=Q4}
C {devices/lab_pin.sym} -130 150 0 0 {name=p24 sig_type=std_logic lab=Q3}
C {devices/lab_pin.sym} 10 150 0 0 {name=p25 sig_type=std_logic lab=Q2}
C {devices/lab_pin.sym} 160 150 0 0 {name=p26 sig_type=std_logic lab=Q1}
C {devices/lab_pin.sym} 310 150 0 0 {name=p27 sig_type=std_logic lab=Q0}
C {res.sym} -160 -100 0 0 {name=R1
value=0.01
footprint=1206
device=resistor
m=1}
C {devices/lab_pin.sym} -130 20 0 0 {name=p28 sig_type=std_logic lab=Q7}
